/**
 * The timezone a country "lives in", for defaulting a user's timezone from their country.
 *
 * ## Why a table
 *
 * Nothing in Intl maps a country to a zone, and the country data we do have (`country-state-city`,
 * client only) lists a country's zones alphabetically — so "the first zone" puts the whole US on
 * `America/Adak` (the Aleutians) and Australia on `Antarctica/Macquarie`. This table names one main
 * zone per country: the only zone for 218 of them, and the capital's or most-populous zone for the
 * 30 that span several. Antarctica has no meaningful answer and is absent.
 *
 * Generated from `country-state-city` plus those 30 choices; the same table lives in
 * `server/src/lib/countryTimezones.ts` and `Client-v2/src/lib/country-timezones.ts` — keep them in
 * step (no monorepo package yet to share it through).
 *
 * ## Spelling
 *
 * Zones are stored with their modern IANA names (`Asia/Kolkata`, `Europe/Kyiv`). V8's
 * `Intl.supportedValuesOf("timeZone")` — which both the server validator and the Profile dropdown
 * use — lists the legacy aliases (`Asia/Calcutta`, `Europe/Kiev`), while Firefox lists the modern
 * ones. `toSupportedTimezone` translates to whichever spelling the running engine lists, so a
 * value never fails validation or renders as a blank select just because of an alias.
 */
export const COUNTRY_MAIN_TIMEZONE: Readonly<Record<string, string>> = {
  AF: "Asia/Kabul",
  AX: "Europe/Mariehamn",
  AL: "Europe/Tirane",
  DZ: "Africa/Algiers",
  AS: "Pacific/Pago_Pago",
  AD: "Europe/Andorra",
  AO: "Africa/Luanda",
  AI: "America/Anguilla",
  AG: "America/Antigua",
  AR: "America/Argentina/Buenos_Aires",
  AM: "Asia/Yerevan",
  AW: "America/Aruba",
  AU: "Australia/Sydney",
  AT: "Europe/Vienna",
  AZ: "Asia/Baku",
  BS: "America/Nassau",
  BH: "Asia/Bahrain",
  BD: "Asia/Dhaka",
  BB: "America/Barbados",
  BY: "Europe/Minsk",
  BE: "Europe/Brussels",
  BZ: "America/Belize",
  BJ: "Africa/Porto-Novo",
  BM: "Atlantic/Bermuda",
  BT: "Asia/Thimphu",
  BO: "America/La_Paz",
  BA: "Europe/Sarajevo",
  BW: "Africa/Gaborone",
  BV: "Europe/Oslo",
  BR: "America/Sao_Paulo",
  IO: "Indian/Chagos",
  BN: "Asia/Brunei",
  BG: "Europe/Sofia",
  BF: "Africa/Ouagadougou",
  BI: "Africa/Bujumbura",
  KH: "Asia/Phnom_Penh",
  CM: "Africa/Douala",
  CA: "America/Toronto",
  CV: "Atlantic/Cape_Verde",
  KY: "America/Cayman",
  CF: "Africa/Bangui",
  TD: "Africa/Ndjamena",
  CL: "America/Santiago",
  CN: "Asia/Shanghai",
  CX: "Indian/Christmas",
  CC: "Indian/Cocos",
  CO: "America/Bogota",
  KM: "Indian/Comoro",
  CG: "Africa/Brazzaville",
  CD: "Africa/Kinshasa",
  CK: "Pacific/Rarotonga",
  CR: "America/Costa_Rica",
  CI: "Africa/Abidjan",
  HR: "Europe/Zagreb",
  CU: "America/Havana",
  CY: "Asia/Nicosia",
  CZ: "Europe/Prague",
  DK: "Europe/Copenhagen",
  DJ: "Africa/Djibouti",
  DM: "America/Dominica",
  DO: "America/Santo_Domingo",
  TL: "Asia/Dili",
  EC: "America/Guayaquil",
  EG: "Africa/Cairo",
  SV: "America/El_Salvador",
  GQ: "Africa/Malabo",
  ER: "Africa/Asmara",
  EE: "Europe/Tallinn",
  ET: "Africa/Addis_Ababa",
  FK: "Atlantic/Stanley",
  FO: "Atlantic/Faroe",
  FJ: "Pacific/Fiji",
  FI: "Europe/Helsinki",
  FR: "Europe/Paris",
  GF: "America/Cayenne",
  PF: "Pacific/Tahiti",
  TF: "Indian/Kerguelen",
  GA: "Africa/Libreville",
  GM: "Africa/Banjul",
  GE: "Asia/Tbilisi",
  DE: "Europe/Berlin",
  GH: "Africa/Accra",
  GI: "Europe/Gibraltar",
  GR: "Europe/Athens",
  GL: "America/Nuuk",
  GD: "America/Grenada",
  GP: "America/Guadeloupe",
  GU: "Pacific/Guam",
  GT: "America/Guatemala",
  GG: "Europe/Guernsey",
  GN: "Africa/Conakry",
  GW: "Africa/Bissau",
  GY: "America/Guyana",
  HT: "America/Port-au-Prince",
  HM: "Indian/Kerguelen",
  HN: "America/Tegucigalpa",
  HK: "Asia/Hong_Kong",
  HU: "Europe/Budapest",
  IS: "Atlantic/Reykjavik",
  IN: "Asia/Kolkata",
  ID: "Asia/Jakarta",
  IR: "Asia/Tehran",
  IQ: "Asia/Baghdad",
  IE: "Europe/Dublin",
  IL: "Asia/Jerusalem",
  IT: "Europe/Rome",
  JM: "America/Jamaica",
  JP: "Asia/Tokyo",
  JE: "Europe/Jersey",
  JO: "Asia/Amman",
  KZ: "Asia/Almaty",
  KE: "Africa/Nairobi",
  KI: "Pacific/Tarawa",
  KP: "Asia/Pyongyang",
  KR: "Asia/Seoul",
  KW: "Asia/Kuwait",
  KG: "Asia/Bishkek",
  LA: "Asia/Vientiane",
  LV: "Europe/Riga",
  LB: "Asia/Beirut",
  LS: "Africa/Maseru",
  LR: "Africa/Monrovia",
  LY: "Africa/Tripoli",
  LI: "Europe/Vaduz",
  LT: "Europe/Vilnius",
  LU: "Europe/Luxembourg",
  MO: "Asia/Macau",
  MK: "Europe/Skopje",
  MG: "Indian/Antananarivo",
  MW: "Africa/Blantyre",
  MY: "Asia/Kuala_Lumpur",
  MV: "Indian/Maldives",
  ML: "Africa/Bamako",
  MT: "Europe/Malta",
  IM: "Europe/Isle_of_Man",
  MH: "Pacific/Majuro",
  MQ: "America/Martinique",
  MR: "Africa/Nouakchott",
  MU: "Indian/Mauritius",
  YT: "Indian/Mayotte",
  MX: "America/Mexico_City",
  FM: "Pacific/Pohnpei",
  MD: "Europe/Chisinau",
  MC: "Europe/Monaco",
  MN: "Asia/Ulaanbaatar",
  ME: "Europe/Podgorica",
  MS: "America/Montserrat",
  MA: "Africa/Casablanca",
  MZ: "Africa/Maputo",
  MM: "Asia/Yangon",
  NA: "Africa/Windhoek",
  NR: "Pacific/Nauru",
  NP: "Asia/Kathmandu",
  BQ: "America/Anguilla",
  NL: "Europe/Amsterdam",
  NC: "Pacific/Noumea",
  NZ: "Pacific/Auckland",
  NI: "America/Managua",
  NE: "Africa/Niamey",
  NG: "Africa/Lagos",
  NU: "Pacific/Niue",
  NF: "Pacific/Norfolk",
  MP: "Pacific/Saipan",
  NO: "Europe/Oslo",
  OM: "Asia/Muscat",
  PK: "Asia/Karachi",
  PW: "Pacific/Palau",
  PS: "Asia/Gaza",
  PA: "America/Panama",
  PG: "Pacific/Port_Moresby",
  PY: "America/Asuncion",
  PE: "America/Lima",
  PH: "Asia/Manila",
  PN: "Pacific/Pitcairn",
  PL: "Europe/Warsaw",
  PT: "Europe/Lisbon",
  PR: "America/Puerto_Rico",
  QA: "Asia/Qatar",
  RE: "Indian/Reunion",
  RO: "Europe/Bucharest",
  RU: "Europe/Moscow",
  RW: "Africa/Kigali",
  SH: "Atlantic/St_Helena",
  KN: "America/St_Kitts",
  LC: "America/St_Lucia",
  PM: "America/Miquelon",
  VC: "America/St_Vincent",
  BL: "America/St_Barthelemy",
  MF: "America/Marigot",
  WS: "Pacific/Apia",
  SM: "Europe/San_Marino",
  ST: "Africa/Sao_Tome",
  SA: "Asia/Riyadh",
  SN: "Africa/Dakar",
  RS: "Europe/Belgrade",
  SC: "Indian/Mahe",
  SL: "Africa/Freetown",
  SG: "Asia/Singapore",
  SK: "Europe/Bratislava",
  SI: "Europe/Ljubljana",
  SB: "Pacific/Guadalcanal",
  SO: "Africa/Mogadishu",
  ZA: "Africa/Johannesburg",
  GS: "Atlantic/South_Georgia",
  SS: "Africa/Juba",
  ES: "Europe/Madrid",
  LK: "Asia/Colombo",
  SD: "Africa/Khartoum",
  SR: "America/Paramaribo",
  SJ: "Arctic/Longyearbyen",
  SZ: "Africa/Mbabane",
  SE: "Europe/Stockholm",
  CH: "Europe/Zurich",
  SY: "Asia/Damascus",
  TW: "Asia/Taipei",
  TJ: "Asia/Dushanbe",
  TZ: "Africa/Dar_es_Salaam",
  TH: "Asia/Bangkok",
  TG: "Africa/Lome",
  TK: "Pacific/Fakaofo",
  TO: "Pacific/Tongatapu",
  TT: "America/Port_of_Spain",
  TN: "Africa/Tunis",
  TR: "Europe/Istanbul",
  TM: "Asia/Ashgabat",
  TC: "America/Grand_Turk",
  TV: "Pacific/Funafuti",
  UG: "Africa/Kampala",
  UA: "Europe/Kyiv",
  AE: "Asia/Dubai",
  GB: "Europe/London",
  US: "America/New_York",
  UM: "Pacific/Midway",
  UY: "America/Montevideo",
  UZ: "Asia/Tashkent",
  VU: "Pacific/Efate",
  VA: "Europe/Vatican",
  VE: "America/Caracas",
  VN: "Asia/Ho_Chi_Minh",
  VG: "America/Tortola",
  VI: "America/St_Thomas",
  WF: "Pacific/Wallis",
  EH: "Africa/El_Aaiun",
  YE: "Asia/Aden",
  ZM: "Africa/Lusaka",
  ZW: "Africa/Harare",
  XK: "Europe/Belgrade",
  CW: "America/Curacao",
  SX: "America/Anguilla",
};

/**
 * `zone` spelled the way `supported` spells it ("Asia/Kolkata" ↔ "Asia/Calcutta"), or null when
 * the engine doesn't know the zone at all.
 */
export function toSupportedTimezone(zone: string, supported: ReadonlySet<string>): string | null {
  if (supported.has(zone)) return zone;
  try {
    const canonical = new Intl.DateTimeFormat("en-US", { timeZone: zone }).resolvedOptions()
      .timeZone;
    return supported.has(canonical) ? canonical : null;
  } catch {
    return null;
  }
}

/** The main timezone for an ISO 3166-1 alpha-2 country, in `supported`'s spelling; null if none. */
export function defaultTimezoneForCountry(
  country: string | null | undefined,
  supported: ReadonlySet<string>,
): string | null {
  if (!country) return null;
  const zone = COUNTRY_MAIN_TIMEZONE[country.toUpperCase()];
  return zone ? toSupportedTimezone(zone, supported) : null;
}
