/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsCapturedSlugRouteImport } from './routes/leads-captured.$slug'
import { Route as AuthHandoffRouteImport } from './routes/auth.handoff'
import { Route as AppShortLinksRouteImport } from './routes/_app/short-links'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSchedulerRouteImport } from './routes/_app/scheduler'
import { Route as AppRbacMasterRouteImport } from './routes/_app/rbac-master'
import { Route as AppPlatformAdminsRouteImport } from './routes/_app/platform-admins'
import { Route as AppLeadsCapturedRouteImport } from './routes/_app/leads-captured'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCreatorsProgramRouteImport } from './routes/_app/creators-program'
import { Route as AppBioLinkRouteImport } from './routes/_app/bio-link'
import { Route as AppBillingsRouteImport } from './routes/_app/billings'
import { Route as AppApiDocsRouteImport } from './routes/_app/api-docs'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAiTokensMasterRouteImport } from './routes/_app/ai-tokens-master'
import { Route as AppAgencyRouteImport } from './routes/_app/agency'
import { Route as AppAffiliateRouteImport } from './routes/_app/affiliate'
import { Route as AppAccessManagementRouteImport } from './routes/_app/access-management'
import { Route as AppTeamIndexRouteImport } from './routes/_app/team.index'
import { Route as AppPackagesIndexRouteImport } from './routes/_app/packages.index'
import { Route as AppModuleRegistryIndexRouteImport } from './routes/_app/module-registry.index'
import { Route as AppAutomationsIndexRouteImport } from './routes/_app/automations.index'
import { Route as OauthMetaCompleteRouteImport } from './routes/oauth.meta.complete'
import { Route as AuthGoogleCompleteRouteImport } from './routes/auth.google.complete'
import { Route as AppTeamInviteRouteImport } from './routes/_app/team.invite'
import { Route as AppPluginsKeyRouteImport } from './routes/_app/plugins.$key'
import { Route as AppPackagesNewRouteImport } from './routes/_app/packages.new'
import { Route as AppPackagesAssignRouteImport } from './routes/_app/packages.assign'
import { Route as AppPackagesPackageIdRouteImport } from './routes/_app/packages.$packageId'
import { Route as AppModuleRegistryNewRouteImport } from './routes/_app/module-registry.new'
import { Route as AppModuleRegistryDocsRouteImport } from './routes/_app/module-registry.docs'
import { Route as AppModuleRegistryParentIdRouteImport } from './routes/_app/module-registry.$parentId'
import { Route as AppAutomationsNewRouteImport } from './routes/_app/automations.new'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin.users'
import { Route as AppAdminPluginsRouteImport } from './routes/_app/admin.plugins'
import { Route as AppAdminImpersonationRouteImport } from './routes/_app/admin.impersonation'
import { Route as AppAdminEmailTemplatesRouteImport } from './routes/_app/admin.email-templates'
import { Route as AppAdminCreatorsRouteImport } from './routes/_app/admin.creators'
import { Route as AppAdminCreatorManagementRouteImport } from './routes/_app/admin.creator-management'
import { Route as AppAdminCapabilitiesRouteImport } from './routes/_app/admin.capabilities'
import { Route as AppAdminAffiliatesRouteImport } from './routes/_app/admin.affiliates'
import { Route as AppAdminUsersUserIdRouteImport } from './routes/_app/admin.users.$userId'
import { Route as AppAdminPluginsSigningKeysRouteImport } from './routes/_app/admin.plugins_.signing-keys'
import { Route as AppAdminPluginsDocsRouteImport } from './routes/_app/admin.plugins_.docs'
import { Route as AppAdminCreatorsProfileIdRouteImport } from './routes/_app/admin.creators.$profileId'
import { Route as AppAdminCreatorManagementProfileIdRouteImport } from './routes/_app/admin.creator-management.$profileId'
import { Route as AppAdminUsersUserIdIndexRouteImport } from './routes/_app/admin.users.$userId.index'
import { Route as AppAdminUsersUserIdWorkspacesRouteImport } from './routes/_app/admin.users.$userId.workspaces'
import { Route as AppAdminUsersUserIdSessionsRouteImport } from './routes/_app/admin.users.$userId.sessions'
import { Route as AppAdminUsersUserIdImpersonationRouteImport } from './routes/_app/admin.users.$userId.impersonation'
import { Route as AppAdminUsersUserIdBillingRouteImport } from './routes/_app/admin.users.$userId.billing'
import { Route as AppAdminUsersUserIdAiApiRouteImport } from './routes/_app/admin.users.$userId.ai-api'
import { Route as AppAdminUsersUserIdActivityRouteImport } from './routes/_app/admin.users.$userId.activity'
import { Route as AppAdminUsersUserIdWorkspacesWsIdRouteImport } from './routes/_app/admin.users.$userId.workspaces_.$wsId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsCapturedSlugRoute = LeadsCapturedSlugRouteImport.update({
  id: '/leads-captured/$slug',
  path: '/leads-captured/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthHandoffRoute = AuthHandoffRouteImport.update({
  id: '/auth/handoff',
  path: '/auth/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShortLinksRoute = AppShortLinksRouteImport.update({
  id: '/short-links',
  path: '/short-links',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSchedulerRoute = AppSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AppRoute,
} as any)
const AppRbacMasterRoute = AppRbacMasterRouteImport.update({
  id: '/rbac-master',
  path: '/rbac-master',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformAdminsRoute = AppPlatformAdminsRouteImport.update({
  id: '/platform-admins',
  path: '/platform-admins',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsCapturedRoute = AppLeadsCapturedRouteImport.update({
  id: '/leads-captured',
  path: '/leads-captured',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreatorsProgramRoute = AppCreatorsProgramRouteImport.update({
  id: '/creators-program',
  path: '/creators-program',
  getParentRoute: () => AppRoute,
} as any)
const AppBioLinkRoute = AppBioLinkRouteImport.update({
  id: '/bio-link',
  path: '/bio-link',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingsRoute = AppBillingsRouteImport.update({
  id: '/billings',
  path: '/billings',
  getParentRoute: () => AppRoute,
} as any)
const AppApiDocsRoute = AppApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiTokensMasterRoute = AppAiTokensMasterRouteImport.update({
  id: '/ai-tokens-master',
  path: '/ai-tokens-master',
  getParentRoute: () => AppRoute,
} as any)
const AppAgencyRoute = AppAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateRoute = AppAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessManagementRoute = AppAccessManagementRouteImport.update({
  id: '/access-management',
  path: '/access-management',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamIndexRoute = AppTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesIndexRoute = AppPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => AppRoute,
} as any)
const AppModuleRegistryIndexRoute = AppModuleRegistryIndexRouteImport.update({
  id: '/module-registry/',
  path: '/module-registry/',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsIndexRoute = AppAutomationsIndexRouteImport.update({
  id: '/automations/',
  path: '/automations/',
  getParentRoute: () => AppRoute,
} as any)
const OauthMetaCompleteRoute = OauthMetaCompleteRouteImport.update({
  id: '/oauth/meta/complete',
  path: '/oauth/meta/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCompleteRoute = AuthGoogleCompleteRouteImport.update({
  id: '/auth/google/complete',
  path: '/auth/google/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamInviteRoute = AppTeamInviteRouteImport.update({
  id: '/team/invite',
  path: '/team/invite',
  getParentRoute: () => AppRoute,
} as any)
const AppPluginsKeyRoute = AppPluginsKeyRouteImport.update({
  id: '/plugins/$key',
  path: '/plugins/$key',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesNewRoute = AppPackagesNewRouteImport.update({
  id: '/packages/new',
  path: '/packages/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesAssignRoute = AppPackagesAssignRouteImport.update({
  id: '/packages/assign',
  path: '/packages/assign',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesPackageIdRoute = AppPackagesPackageIdRouteImport.update({
  id: '/packages/$packageId',
  path: '/packages/$packageId',
  getParentRoute: () => AppRoute,
} as any)
const AppModuleRegistryNewRoute = AppModuleRegistryNewRouteImport.update({
  id: '/module-registry/new',
  path: '/module-registry/new',
  getParentRoute: () => AppRoute,
} as any)
const AppModuleRegistryDocsRoute = AppModuleRegistryDocsRouteImport.update({
  id: '/module-registry/docs',
  path: '/module-registry/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppModuleRegistryParentIdRoute =
  AppModuleRegistryParentIdRouteImport.update({
    id: '/module-registry/$parentId',
    path: '/module-registry/$parentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAutomationsNewRoute = AppAutomationsNewRouteImport.update({
  id: '/automations/new',
  path: '/automations/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPluginsRoute = AppAdminPluginsRouteImport.update({
  id: '/admin/plugins',
  path: '/admin/plugins',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminImpersonationRoute = AppAdminImpersonationRouteImport.update({
  id: '/admin/impersonation',
  path: '/admin/impersonation',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmailTemplatesRoute = AppAdminEmailTemplatesRouteImport.update({
  id: '/admin/email-templates',
  path: '/admin/email-templates',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCreatorsRoute = AppAdminCreatorsRouteImport.update({
  id: '/admin/creators',
  path: '/admin/creators',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCreatorManagementRoute =
  AppAdminCreatorManagementRouteImport.update({
    id: '/admin/creator-management',
    path: '/admin/creator-management',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminCapabilitiesRoute = AppAdminCapabilitiesRouteImport.update({
  id: '/admin/capabilities',
  path: '/admin/capabilities',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAffiliatesRoute = AppAdminAffiliatesRouteImport.update({
  id: '/admin/affiliates',
  path: '/admin/affiliates',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersUserIdRoute = AppAdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppAdminUsersRoute,
} as any)
const AppAdminPluginsSigningKeysRoute =
  AppAdminPluginsSigningKeysRouteImport.update({
    id: '/admin/plugins_/signing-keys',
    path: '/admin/plugins/signing-keys',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminPluginsDocsRoute = AppAdminPluginsDocsRouteImport.update({
  id: '/admin/plugins_/docs',
  path: '/admin/plugins/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCreatorsProfileIdRoute =
  AppAdminCreatorsProfileIdRouteImport.update({
    id: '/$profileId',
    path: '/$profileId',
    getParentRoute: () => AppAdminCreatorsRoute,
  } as any)
const AppAdminCreatorManagementProfileIdRoute =
  AppAdminCreatorManagementProfileIdRouteImport.update({
    id: '/$profileId',
    path: '/$profileId',
    getParentRoute: () => AppAdminCreatorManagementRoute,
  } as any)
const AppAdminUsersUserIdIndexRoute =
  AppAdminUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAdminUsersUserIdRoute,
  } as any)
const AppAdminUsersUserIdWorkspacesRoute =
  AppAdminUsersUserIdWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AppAdminUsersUserIdRoute,
  } as any)
const AppAdminUsersUserIdSessionsRoute =
  AppAdminUsersUserIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AppAdminUsersUserIdRoute,
  } as any)
const AppAdminUsersUserIdImpersonationRoute =
  AppAdminUsersUserIdImpersonationRouteImport.update({
    id: '/impersonation',
    path: '/impersonation',
    getParentRoute: () => AppAdminUsersUserIdRoute,
  } as any)
const AppAdminUsersUserIdBillingRoute =
  AppAdminUsersUserIdBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppAdminUsersUserIdRoute,
  } as any)
const AppAdminUsersUserIdAiApiRoute =
  AppAdminUsersUserIdAiApiRouteImport.update({
    id: '/ai-api',
    path: '/ai-api',
    getParentRoute: () => AppAdminUsersUserIdRoute,
  } as any)
const AppAdminUsersUserIdActivityRoute =
  AppAdminUsersUserIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AppAdminUsersUserIdRoute,
  } as any)
const AppAdminUsersUserIdWorkspacesWsIdRoute =
  AppAdminUsersUserIdWorkspacesWsIdRouteImport.update({
    id: '/workspaces_/$wsId',
    path: '/workspaces/$wsId',
    getParentRoute: () => AppAdminUsersUserIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/checkout': typeof CheckoutRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/access-management': typeof AppAccessManagementRoute
  '/affiliate': typeof AppAffiliateRoute
  '/agency': typeof AppAgencyRoute
  '/ai-tokens-master': typeof AppAiTokensMasterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api-docs': typeof AppApiDocsRoute
  '/billings': typeof AppBillingsRoute
  '/bio-link': typeof AppBioLinkRoute
  '/creators-program': typeof AppCreatorsProgramRoute
  '/dashboard': typeof AppDashboardRoute
  '/leads-captured': typeof AppLeadsCapturedRoute
  '/platform-admins': typeof AppPlatformAdminsRoute
  '/rbac-master': typeof AppRbacMasterRoute
  '/scheduler': typeof AppSchedulerRoute
  '/settings': typeof AppSettingsRoute
  '/short-links': typeof AppShortLinksRoute
  '/auth/handoff': typeof AuthHandoffRoute
  '/leads-captured/$slug': typeof LeadsCapturedSlugRoute
  '/admin/affiliates': typeof AppAdminAffiliatesRoute
  '/admin/capabilities': typeof AppAdminCapabilitiesRoute
  '/admin/creator-management': typeof AppAdminCreatorManagementRouteWithChildren
  '/admin/creators': typeof AppAdminCreatorsRouteWithChildren
  '/admin/email-templates': typeof AppAdminEmailTemplatesRoute
  '/admin/impersonation': typeof AppAdminImpersonationRoute
  '/admin/plugins': typeof AppAdminPluginsRoute
  '/admin/users': typeof AppAdminUsersRouteWithChildren
  '/automations/new': typeof AppAutomationsNewRoute
  '/module-registry/$parentId': typeof AppModuleRegistryParentIdRoute
  '/module-registry/docs': typeof AppModuleRegistryDocsRoute
  '/module-registry/new': typeof AppModuleRegistryNewRoute
  '/packages/$packageId': typeof AppPackagesPackageIdRoute
  '/packages/assign': typeof AppPackagesAssignRoute
  '/packages/new': typeof AppPackagesNewRoute
  '/plugins/$key': typeof AppPluginsKeyRoute
  '/team/invite': typeof AppTeamInviteRoute
  '/auth/google/complete': typeof AuthGoogleCompleteRoute
  '/oauth/meta/complete': typeof OauthMetaCompleteRoute
  '/automations/': typeof AppAutomationsIndexRoute
  '/module-registry/': typeof AppModuleRegistryIndexRoute
  '/packages/': typeof AppPackagesIndexRoute
  '/team/': typeof AppTeamIndexRoute
  '/admin/creator-management/$profileId': typeof AppAdminCreatorManagementProfileIdRoute
  '/admin/creators/$profileId': typeof AppAdminCreatorsProfileIdRoute
  '/admin/plugins/docs': typeof AppAdminPluginsDocsRoute
  '/admin/plugins/signing-keys': typeof AppAdminPluginsSigningKeysRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRouteWithChildren
  '/admin/users/$userId/activity': typeof AppAdminUsersUserIdActivityRoute
  '/admin/users/$userId/ai-api': typeof AppAdminUsersUserIdAiApiRoute
  '/admin/users/$userId/billing': typeof AppAdminUsersUserIdBillingRoute
  '/admin/users/$userId/impersonation': typeof AppAdminUsersUserIdImpersonationRoute
  '/admin/users/$userId/sessions': typeof AppAdminUsersUserIdSessionsRoute
  '/admin/users/$userId/workspaces': typeof AppAdminUsersUserIdWorkspacesRoute
  '/admin/users/$userId/': typeof AppAdminUsersUserIdIndexRoute
  '/admin/users/$userId/workspaces/$wsId': typeof AppAdminUsersUserIdWorkspacesWsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/checkout': typeof CheckoutRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/access-management': typeof AppAccessManagementRoute
  '/affiliate': typeof AppAffiliateRoute
  '/agency': typeof AppAgencyRoute
  '/ai-tokens-master': typeof AppAiTokensMasterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api-docs': typeof AppApiDocsRoute
  '/billings': typeof AppBillingsRoute
  '/bio-link': typeof AppBioLinkRoute
  '/creators-program': typeof AppCreatorsProgramRoute
  '/dashboard': typeof AppDashboardRoute
  '/leads-captured': typeof AppLeadsCapturedRoute
  '/platform-admins': typeof AppPlatformAdminsRoute
  '/rbac-master': typeof AppRbacMasterRoute
  '/scheduler': typeof AppSchedulerRoute
  '/settings': typeof AppSettingsRoute
  '/short-links': typeof AppShortLinksRoute
  '/auth/handoff': typeof AuthHandoffRoute
  '/leads-captured/$slug': typeof LeadsCapturedSlugRoute
  '/admin/affiliates': typeof AppAdminAffiliatesRoute
  '/admin/capabilities': typeof AppAdminCapabilitiesRoute
  '/admin/creator-management': typeof AppAdminCreatorManagementRouteWithChildren
  '/admin/creators': typeof AppAdminCreatorsRouteWithChildren
  '/admin/email-templates': typeof AppAdminEmailTemplatesRoute
  '/admin/impersonation': typeof AppAdminImpersonationRoute
  '/admin/plugins': typeof AppAdminPluginsRoute
  '/admin/users': typeof AppAdminUsersRouteWithChildren
  '/automations/new': typeof AppAutomationsNewRoute
  '/module-registry/$parentId': typeof AppModuleRegistryParentIdRoute
  '/module-registry/docs': typeof AppModuleRegistryDocsRoute
  '/module-registry/new': typeof AppModuleRegistryNewRoute
  '/packages/$packageId': typeof AppPackagesPackageIdRoute
  '/packages/assign': typeof AppPackagesAssignRoute
  '/packages/new': typeof AppPackagesNewRoute
  '/plugins/$key': typeof AppPluginsKeyRoute
  '/team/invite': typeof AppTeamInviteRoute
  '/auth/google/complete': typeof AuthGoogleCompleteRoute
  '/oauth/meta/complete': typeof OauthMetaCompleteRoute
  '/automations': typeof AppAutomationsIndexRoute
  '/module-registry': typeof AppModuleRegistryIndexRoute
  '/packages': typeof AppPackagesIndexRoute
  '/team': typeof AppTeamIndexRoute
  '/admin/creator-management/$profileId': typeof AppAdminCreatorManagementProfileIdRoute
  '/admin/creators/$profileId': typeof AppAdminCreatorsProfileIdRoute
  '/admin/plugins/docs': typeof AppAdminPluginsDocsRoute
  '/admin/plugins/signing-keys': typeof AppAdminPluginsSigningKeysRoute
  '/admin/users/$userId/activity': typeof AppAdminUsersUserIdActivityRoute
  '/admin/users/$userId/ai-api': typeof AppAdminUsersUserIdAiApiRoute
  '/admin/users/$userId/billing': typeof AppAdminUsersUserIdBillingRoute
  '/admin/users/$userId/impersonation': typeof AppAdminUsersUserIdImpersonationRoute
  '/admin/users/$userId/sessions': typeof AppAdminUsersUserIdSessionsRoute
  '/admin/users/$userId/workspaces': typeof AppAdminUsersUserIdWorkspacesRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdIndexRoute
  '/admin/users/$userId/workspaces/$wsId': typeof AppAdminUsersUserIdWorkspacesWsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/checkout': typeof CheckoutRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/_app/access-management': typeof AppAccessManagementRoute
  '/_app/affiliate': typeof AppAffiliateRoute
  '/_app/agency': typeof AppAgencyRoute
  '/_app/ai-tokens-master': typeof AppAiTokensMasterRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/api-docs': typeof AppApiDocsRoute
  '/_app/billings': typeof AppBillingsRoute
  '/_app/bio-link': typeof AppBioLinkRoute
  '/_app/creators-program': typeof AppCreatorsProgramRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leads-captured': typeof AppLeadsCapturedRoute
  '/_app/platform-admins': typeof AppPlatformAdminsRoute
  '/_app/rbac-master': typeof AppRbacMasterRoute
  '/_app/scheduler': typeof AppSchedulerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/short-links': typeof AppShortLinksRoute
  '/auth/handoff': typeof AuthHandoffRoute
  '/leads-captured/$slug': typeof LeadsCapturedSlugRoute
  '/_app/admin/affiliates': typeof AppAdminAffiliatesRoute
  '/_app/admin/capabilities': typeof AppAdminCapabilitiesRoute
  '/_app/admin/creator-management': typeof AppAdminCreatorManagementRouteWithChildren
  '/_app/admin/creators': typeof AppAdminCreatorsRouteWithChildren
  '/_app/admin/email-templates': typeof AppAdminEmailTemplatesRoute
  '/_app/admin/impersonation': typeof AppAdminImpersonationRoute
  '/_app/admin/plugins': typeof AppAdminPluginsRoute
  '/_app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/_app/automations/new': typeof AppAutomationsNewRoute
  '/_app/module-registry/$parentId': typeof AppModuleRegistryParentIdRoute
  '/_app/module-registry/docs': typeof AppModuleRegistryDocsRoute
  '/_app/module-registry/new': typeof AppModuleRegistryNewRoute
  '/_app/packages/$packageId': typeof AppPackagesPackageIdRoute
  '/_app/packages/assign': typeof AppPackagesAssignRoute
  '/_app/packages/new': typeof AppPackagesNewRoute
  '/_app/plugins/$key': typeof AppPluginsKeyRoute
  '/_app/team/invite': typeof AppTeamInviteRoute
  '/auth/google/complete': typeof AuthGoogleCompleteRoute
  '/oauth/meta/complete': typeof OauthMetaCompleteRoute
  '/_app/automations/': typeof AppAutomationsIndexRoute
  '/_app/module-registry/': typeof AppModuleRegistryIndexRoute
  '/_app/packages/': typeof AppPackagesIndexRoute
  '/_app/team/': typeof AppTeamIndexRoute
  '/_app/admin/creator-management/$profileId': typeof AppAdminCreatorManagementProfileIdRoute
  '/_app/admin/creators/$profileId': typeof AppAdminCreatorsProfileIdRoute
  '/_app/admin/plugins_/docs': typeof AppAdminPluginsDocsRoute
  '/_app/admin/plugins_/signing-keys': typeof AppAdminPluginsSigningKeysRoute
  '/_app/admin/users/$userId': typeof AppAdminUsersUserIdRouteWithChildren
  '/_app/admin/users/$userId/activity': typeof AppAdminUsersUserIdActivityRoute
  '/_app/admin/users/$userId/ai-api': typeof AppAdminUsersUserIdAiApiRoute
  '/_app/admin/users/$userId/billing': typeof AppAdminUsersUserIdBillingRoute
  '/_app/admin/users/$userId/impersonation': typeof AppAdminUsersUserIdImpersonationRoute
  '/_app/admin/users/$userId/sessions': typeof AppAdminUsersUserIdSessionsRoute
  '/_app/admin/users/$userId/workspaces': typeof AppAdminUsersUserIdWorkspacesRoute
  '/_app/admin/users/$userId/': typeof AppAdminUsersUserIdIndexRoute
  '/_app/admin/users/$userId/workspaces_/$wsId': typeof AppAdminUsersUserIdWorkspacesWsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/checkout'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/access-management'
    | '/affiliate'
    | '/agency'
    | '/ai-tokens-master'
    | '/analytics'
    | '/api-docs'
    | '/billings'
    | '/bio-link'
    | '/creators-program'
    | '/dashboard'
    | '/leads-captured'
    | '/platform-admins'
    | '/rbac-master'
    | '/scheduler'
    | '/settings'
    | '/short-links'
    | '/auth/handoff'
    | '/leads-captured/$slug'
    | '/admin/affiliates'
    | '/admin/capabilities'
    | '/admin/creator-management'
    | '/admin/creators'
    | '/admin/email-templates'
    | '/admin/impersonation'
    | '/admin/plugins'
    | '/admin/users'
    | '/automations/new'
    | '/module-registry/$parentId'
    | '/module-registry/docs'
    | '/module-registry/new'
    | '/packages/$packageId'
    | '/packages/assign'
    | '/packages/new'
    | '/plugins/$key'
    | '/team/invite'
    | '/auth/google/complete'
    | '/oauth/meta/complete'
    | '/automations/'
    | '/module-registry/'
    | '/packages/'
    | '/team/'
    | '/admin/creator-management/$profileId'
    | '/admin/creators/$profileId'
    | '/admin/plugins/docs'
    | '/admin/plugins/signing-keys'
    | '/admin/users/$userId'
    | '/admin/users/$userId/activity'
    | '/admin/users/$userId/ai-api'
    | '/admin/users/$userId/billing'
    | '/admin/users/$userId/impersonation'
    | '/admin/users/$userId/sessions'
    | '/admin/users/$userId/workspaces'
    | '/admin/users/$userId/'
    | '/admin/users/$userId/workspaces/$wsId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/checkout'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/access-management'
    | '/affiliate'
    | '/agency'
    | '/ai-tokens-master'
    | '/analytics'
    | '/api-docs'
    | '/billings'
    | '/bio-link'
    | '/creators-program'
    | '/dashboard'
    | '/leads-captured'
    | '/platform-admins'
    | '/rbac-master'
    | '/scheduler'
    | '/settings'
    | '/short-links'
    | '/auth/handoff'
    | '/leads-captured/$slug'
    | '/admin/affiliates'
    | '/admin/capabilities'
    | '/admin/creator-management'
    | '/admin/creators'
    | '/admin/email-templates'
    | '/admin/impersonation'
    | '/admin/plugins'
    | '/admin/users'
    | '/automations/new'
    | '/module-registry/$parentId'
    | '/module-registry/docs'
    | '/module-registry/new'
    | '/packages/$packageId'
    | '/packages/assign'
    | '/packages/new'
    | '/plugins/$key'
    | '/team/invite'
    | '/auth/google/complete'
    | '/oauth/meta/complete'
    | '/automations'
    | '/module-registry'
    | '/packages'
    | '/team'
    | '/admin/creator-management/$profileId'
    | '/admin/creators/$profileId'
    | '/admin/plugins/docs'
    | '/admin/plugins/signing-keys'
    | '/admin/users/$userId/activity'
    | '/admin/users/$userId/ai-api'
    | '/admin/users/$userId/billing'
    | '/admin/users/$userId/impersonation'
    | '/admin/users/$userId/sessions'
    | '/admin/users/$userId/workspaces'
    | '/admin/users/$userId'
    | '/admin/users/$userId/workspaces/$wsId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/accept-invite'
    | '/checkout'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/_app/access-management'
    | '/_app/affiliate'
    | '/_app/agency'
    | '/_app/ai-tokens-master'
    | '/_app/analytics'
    | '/_app/api-docs'
    | '/_app/billings'
    | '/_app/bio-link'
    | '/_app/creators-program'
    | '/_app/dashboard'
    | '/_app/leads-captured'
    | '/_app/platform-admins'
    | '/_app/rbac-master'
    | '/_app/scheduler'
    | '/_app/settings'
    | '/_app/short-links'
    | '/auth/handoff'
    | '/leads-captured/$slug'
    | '/_app/admin/affiliates'
    | '/_app/admin/capabilities'
    | '/_app/admin/creator-management'
    | '/_app/admin/creators'
    | '/_app/admin/email-templates'
    | '/_app/admin/impersonation'
    | '/_app/admin/plugins'
    | '/_app/admin/users'
    | '/_app/automations/new'
    | '/_app/module-registry/$parentId'
    | '/_app/module-registry/docs'
    | '/_app/module-registry/new'
    | '/_app/packages/$packageId'
    | '/_app/packages/assign'
    | '/_app/packages/new'
    | '/_app/plugins/$key'
    | '/_app/team/invite'
    | '/auth/google/complete'
    | '/oauth/meta/complete'
    | '/_app/automations/'
    | '/_app/module-registry/'
    | '/_app/packages/'
    | '/_app/team/'
    | '/_app/admin/creator-management/$profileId'
    | '/_app/admin/creators/$profileId'
    | '/_app/admin/plugins_/docs'
    | '/_app/admin/plugins_/signing-keys'
    | '/_app/admin/users/$userId'
    | '/_app/admin/users/$userId/activity'
    | '/_app/admin/users/$userId/ai-api'
    | '/_app/admin/users/$userId/billing'
    | '/_app/admin/users/$userId/impersonation'
    | '/_app/admin/users/$userId/sessions'
    | '/_app/admin/users/$userId/workspaces'
    | '/_app/admin/users/$userId/'
    | '/_app/admin/users/$userId/workspaces_/$wsId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  AuthHandoffRoute: typeof AuthHandoffRoute
  LeadsCapturedSlugRoute: typeof LeadsCapturedSlugRoute
  AuthGoogleCompleteRoute: typeof AuthGoogleCompleteRoute
  OauthMetaCompleteRoute: typeof OauthMetaCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads-captured/$slug': {
      id: '/leads-captured/$slug'
      path: '/leads-captured/$slug'
      fullPath: '/leads-captured/$slug'
      preLoaderRoute: typeof LeadsCapturedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/handoff': {
      id: '/auth/handoff'
      path: '/auth/handoff'
      fullPath: '/auth/handoff'
      preLoaderRoute: typeof AuthHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/short-links': {
      id: '/_app/short-links'
      path: '/short-links'
      fullPath: '/short-links'
      preLoaderRoute: typeof AppShortLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scheduler': {
      id: '/_app/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof AppSchedulerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rbac-master': {
      id: '/_app/rbac-master'
      path: '/rbac-master'
      fullPath: '/rbac-master'
      preLoaderRoute: typeof AppRbacMasterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform-admins': {
      id: '/_app/platform-admins'
      path: '/platform-admins'
      fullPath: '/platform-admins'
      preLoaderRoute: typeof AppPlatformAdminsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads-captured': {
      id: '/_app/leads-captured'
      path: '/leads-captured'
      fullPath: '/leads-captured'
      preLoaderRoute: typeof AppLeadsCapturedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creators-program': {
      id: '/_app/creators-program'
      path: '/creators-program'
      fullPath: '/creators-program'
      preLoaderRoute: typeof AppCreatorsProgramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bio-link': {
      id: '/_app/bio-link'
      path: '/bio-link'
      fullPath: '/bio-link'
      preLoaderRoute: typeof AppBioLinkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billings': {
      id: '/_app/billings'
      path: '/billings'
      fullPath: '/billings'
      preLoaderRoute: typeof AppBillingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-docs': {
      id: '/_app/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof AppApiDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-tokens-master': {
      id: '/_app/ai-tokens-master'
      path: '/ai-tokens-master'
      fullPath: '/ai-tokens-master'
      preLoaderRoute: typeof AppAiTokensMasterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agency': {
      id: '/_app/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AppAgencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate': {
      id: '/_app/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AppAffiliateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access-management': {
      id: '/_app/access-management'
      path: '/access-management'
      fullPath: '/access-management'
      preLoaderRoute: typeof AppAccessManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/': {
      id: '/_app/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof AppTeamIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages/': {
      id: '/_app/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof AppPackagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/module-registry/': {
      id: '/_app/module-registry/'
      path: '/module-registry'
      fullPath: '/module-registry/'
      preLoaderRoute: typeof AppModuleRegistryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations/': {
      id: '/_app/automations/'
      path: '/automations'
      fullPath: '/automations/'
      preLoaderRoute: typeof AppAutomationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/meta/complete': {
      id: '/oauth/meta/complete'
      path: '/oauth/meta/complete'
      fullPath: '/oauth/meta/complete'
      preLoaderRoute: typeof OauthMetaCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/complete': {
      id: '/auth/google/complete'
      path: '/auth/google/complete'
      fullPath: '/auth/google/complete'
      preLoaderRoute: typeof AuthGoogleCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team/invite': {
      id: '/_app/team/invite'
      path: '/team/invite'
      fullPath: '/team/invite'
      preLoaderRoute: typeof AppTeamInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plugins/$key': {
      id: '/_app/plugins/$key'
      path: '/plugins/$key'
      fullPath: '/plugins/$key'
      preLoaderRoute: typeof AppPluginsKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages/new': {
      id: '/_app/packages/new'
      path: '/packages/new'
      fullPath: '/packages/new'
      preLoaderRoute: typeof AppPackagesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages/assign': {
      id: '/_app/packages/assign'
      path: '/packages/assign'
      fullPath: '/packages/assign'
      preLoaderRoute: typeof AppPackagesAssignRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages/$packageId': {
      id: '/_app/packages/$packageId'
      path: '/packages/$packageId'
      fullPath: '/packages/$packageId'
      preLoaderRoute: typeof AppPackagesPackageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/module-registry/new': {
      id: '/_app/module-registry/new'
      path: '/module-registry/new'
      fullPath: '/module-registry/new'
      preLoaderRoute: typeof AppModuleRegistryNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/module-registry/docs': {
      id: '/_app/module-registry/docs'
      path: '/module-registry/docs'
      fullPath: '/module-registry/docs'
      preLoaderRoute: typeof AppModuleRegistryDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/module-registry/$parentId': {
      id: '/_app/module-registry/$parentId'
      path: '/module-registry/$parentId'
      fullPath: '/module-registry/$parentId'
      preLoaderRoute: typeof AppModuleRegistryParentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations/new': {
      id: '/_app/automations/new'
      path: '/automations/new'
      fullPath: '/automations/new'
      preLoaderRoute: typeof AppAutomationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/plugins': {
      id: '/_app/admin/plugins'
      path: '/admin/plugins'
      fullPath: '/admin/plugins'
      preLoaderRoute: typeof AppAdminPluginsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/impersonation': {
      id: '/_app/admin/impersonation'
      path: '/admin/impersonation'
      fullPath: '/admin/impersonation'
      preLoaderRoute: typeof AppAdminImpersonationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/email-templates': {
      id: '/_app/admin/email-templates'
      path: '/admin/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AppAdminEmailTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/creators': {
      id: '/_app/admin/creators'
      path: '/admin/creators'
      fullPath: '/admin/creators'
      preLoaderRoute: typeof AppAdminCreatorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/creator-management': {
      id: '/_app/admin/creator-management'
      path: '/admin/creator-management'
      fullPath: '/admin/creator-management'
      preLoaderRoute: typeof AppAdminCreatorManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/capabilities': {
      id: '/_app/admin/capabilities'
      path: '/admin/capabilities'
      fullPath: '/admin/capabilities'
      preLoaderRoute: typeof AppAdminCapabilitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/affiliates': {
      id: '/_app/admin/affiliates'
      path: '/admin/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AppAdminAffiliatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users/$userId': {
      id: '/_app/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AppAdminUsersUserIdRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/_app/admin/plugins_/signing-keys': {
      id: '/_app/admin/plugins_/signing-keys'
      path: '/admin/plugins/signing-keys'
      fullPath: '/admin/plugins/signing-keys'
      preLoaderRoute: typeof AppAdminPluginsSigningKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/plugins_/docs': {
      id: '/_app/admin/plugins_/docs'
      path: '/admin/plugins/docs'
      fullPath: '/admin/plugins/docs'
      preLoaderRoute: typeof AppAdminPluginsDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/creators/$profileId': {
      id: '/_app/admin/creators/$profileId'
      path: '/$profileId'
      fullPath: '/admin/creators/$profileId'
      preLoaderRoute: typeof AppAdminCreatorsProfileIdRouteImport
      parentRoute: typeof AppAdminCreatorsRoute
    }
    '/_app/admin/creator-management/$profileId': {
      id: '/_app/admin/creator-management/$profileId'
      path: '/$profileId'
      fullPath: '/admin/creator-management/$profileId'
      preLoaderRoute: typeof AppAdminCreatorManagementProfileIdRouteImport
      parentRoute: typeof AppAdminCreatorManagementRoute
    }
    '/_app/admin/users/$userId/': {
      id: '/_app/admin/users/$userId/'
      path: '/'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AppAdminUsersUserIdIndexRouteImport
      parentRoute: typeof AppAdminUsersUserIdRoute
    }
    '/_app/admin/users/$userId/workspaces': {
      id: '/_app/admin/users/$userId/workspaces'
      path: '/workspaces'
      fullPath: '/admin/users/$userId/workspaces'
      preLoaderRoute: typeof AppAdminUsersUserIdWorkspacesRouteImport
      parentRoute: typeof AppAdminUsersUserIdRoute
    }
    '/_app/admin/users/$userId/sessions': {
      id: '/_app/admin/users/$userId/sessions'
      path: '/sessions'
      fullPath: '/admin/users/$userId/sessions'
      preLoaderRoute: typeof AppAdminUsersUserIdSessionsRouteImport
      parentRoute: typeof AppAdminUsersUserIdRoute
    }
    '/_app/admin/users/$userId/impersonation': {
      id: '/_app/admin/users/$userId/impersonation'
      path: '/impersonation'
      fullPath: '/admin/users/$userId/impersonation'
      preLoaderRoute: typeof AppAdminUsersUserIdImpersonationRouteImport
      parentRoute: typeof AppAdminUsersUserIdRoute
    }
    '/_app/admin/users/$userId/billing': {
      id: '/_app/admin/users/$userId/billing'
      path: '/billing'
      fullPath: '/admin/users/$userId/billing'
      preLoaderRoute: typeof AppAdminUsersUserIdBillingRouteImport
      parentRoute: typeof AppAdminUsersUserIdRoute
    }
    '/_app/admin/users/$userId/ai-api': {
      id: '/_app/admin/users/$userId/ai-api'
      path: '/ai-api'
      fullPath: '/admin/users/$userId/ai-api'
      preLoaderRoute: typeof AppAdminUsersUserIdAiApiRouteImport
      parentRoute: typeof AppAdminUsersUserIdRoute
    }
    '/_app/admin/users/$userId/activity': {
      id: '/_app/admin/users/$userId/activity'
      path: '/activity'
      fullPath: '/admin/users/$userId/activity'
      preLoaderRoute: typeof AppAdminUsersUserIdActivityRouteImport
      parentRoute: typeof AppAdminUsersUserIdRoute
    }
    '/_app/admin/users/$userId/workspaces_/$wsId': {
      id: '/_app/admin/users/$userId/workspaces_/$wsId'
      path: '/workspaces/$wsId'
      fullPath: '/admin/users/$userId/workspaces/$wsId'
      preLoaderRoute: typeof AppAdminUsersUserIdWorkspacesWsIdRouteImport
      parentRoute: typeof AppAdminUsersUserIdRoute
    }
  }
}

interface AppAdminCreatorManagementRouteChildren {
  AppAdminCreatorManagementProfileIdRoute: typeof AppAdminCreatorManagementProfileIdRoute
}

const AppAdminCreatorManagementRouteChildren: AppAdminCreatorManagementRouteChildren =
  {
    AppAdminCreatorManagementProfileIdRoute:
      AppAdminCreatorManagementProfileIdRoute,
  }

const AppAdminCreatorManagementRouteWithChildren =
  AppAdminCreatorManagementRoute._addFileChildren(
    AppAdminCreatorManagementRouteChildren,
  )

interface AppAdminCreatorsRouteChildren {
  AppAdminCreatorsProfileIdRoute: typeof AppAdminCreatorsProfileIdRoute
}

const AppAdminCreatorsRouteChildren: AppAdminCreatorsRouteChildren = {
  AppAdminCreatorsProfileIdRoute: AppAdminCreatorsProfileIdRoute,
}

const AppAdminCreatorsRouteWithChildren =
  AppAdminCreatorsRoute._addFileChildren(AppAdminCreatorsRouteChildren)

interface AppAdminUsersUserIdRouteChildren {
  AppAdminUsersUserIdActivityRoute: typeof AppAdminUsersUserIdActivityRoute
  AppAdminUsersUserIdAiApiRoute: typeof AppAdminUsersUserIdAiApiRoute
  AppAdminUsersUserIdBillingRoute: typeof AppAdminUsersUserIdBillingRoute
  AppAdminUsersUserIdImpersonationRoute: typeof AppAdminUsersUserIdImpersonationRoute
  AppAdminUsersUserIdSessionsRoute: typeof AppAdminUsersUserIdSessionsRoute
  AppAdminUsersUserIdWorkspacesRoute: typeof AppAdminUsersUserIdWorkspacesRoute
  AppAdminUsersUserIdIndexRoute: typeof AppAdminUsersUserIdIndexRoute
  AppAdminUsersUserIdWorkspacesWsIdRoute: typeof AppAdminUsersUserIdWorkspacesWsIdRoute
}

const AppAdminUsersUserIdRouteChildren: AppAdminUsersUserIdRouteChildren = {
  AppAdminUsersUserIdActivityRoute: AppAdminUsersUserIdActivityRoute,
  AppAdminUsersUserIdAiApiRoute: AppAdminUsersUserIdAiApiRoute,
  AppAdminUsersUserIdBillingRoute: AppAdminUsersUserIdBillingRoute,
  AppAdminUsersUserIdImpersonationRoute: AppAdminUsersUserIdImpersonationRoute,
  AppAdminUsersUserIdSessionsRoute: AppAdminUsersUserIdSessionsRoute,
  AppAdminUsersUserIdWorkspacesRoute: AppAdminUsersUserIdWorkspacesRoute,
  AppAdminUsersUserIdIndexRoute: AppAdminUsersUserIdIndexRoute,
  AppAdminUsersUserIdWorkspacesWsIdRoute:
    AppAdminUsersUserIdWorkspacesWsIdRoute,
}

const AppAdminUsersUserIdRouteWithChildren =
  AppAdminUsersUserIdRoute._addFileChildren(AppAdminUsersUserIdRouteChildren)

interface AppAdminUsersRouteChildren {
  AppAdminUsersUserIdRoute: typeof AppAdminUsersUserIdRouteWithChildren
}

const AppAdminUsersRouteChildren: AppAdminUsersRouteChildren = {
  AppAdminUsersUserIdRoute: AppAdminUsersUserIdRouteWithChildren,
}

const AppAdminUsersRouteWithChildren = AppAdminUsersRoute._addFileChildren(
  AppAdminUsersRouteChildren,
)

interface AppRouteChildren {
  AppAccessManagementRoute: typeof AppAccessManagementRoute
  AppAffiliateRoute: typeof AppAffiliateRoute
  AppAgencyRoute: typeof AppAgencyRoute
  AppAiTokensMasterRoute: typeof AppAiTokensMasterRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApiDocsRoute: typeof AppApiDocsRoute
  AppBillingsRoute: typeof AppBillingsRoute
  AppBioLinkRoute: typeof AppBioLinkRoute
  AppCreatorsProgramRoute: typeof AppCreatorsProgramRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeadsCapturedRoute: typeof AppLeadsCapturedRoute
  AppPlatformAdminsRoute: typeof AppPlatformAdminsRoute
  AppRbacMasterRoute: typeof AppRbacMasterRoute
  AppSchedulerRoute: typeof AppSchedulerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShortLinksRoute: typeof AppShortLinksRoute
  AppAdminAffiliatesRoute: typeof AppAdminAffiliatesRoute
  AppAdminCapabilitiesRoute: typeof AppAdminCapabilitiesRoute
  AppAdminCreatorManagementRoute: typeof AppAdminCreatorManagementRouteWithChildren
  AppAdminCreatorsRoute: typeof AppAdminCreatorsRouteWithChildren
  AppAdminEmailTemplatesRoute: typeof AppAdminEmailTemplatesRoute
  AppAdminImpersonationRoute: typeof AppAdminImpersonationRoute
  AppAdminPluginsRoute: typeof AppAdminPluginsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRouteWithChildren
  AppAutomationsNewRoute: typeof AppAutomationsNewRoute
  AppModuleRegistryParentIdRoute: typeof AppModuleRegistryParentIdRoute
  AppModuleRegistryDocsRoute: typeof AppModuleRegistryDocsRoute
  AppModuleRegistryNewRoute: typeof AppModuleRegistryNewRoute
  AppPackagesPackageIdRoute: typeof AppPackagesPackageIdRoute
  AppPackagesAssignRoute: typeof AppPackagesAssignRoute
  AppPackagesNewRoute: typeof AppPackagesNewRoute
  AppPluginsKeyRoute: typeof AppPluginsKeyRoute
  AppTeamInviteRoute: typeof AppTeamInviteRoute
  AppAutomationsIndexRoute: typeof AppAutomationsIndexRoute
  AppModuleRegistryIndexRoute: typeof AppModuleRegistryIndexRoute
  AppPackagesIndexRoute: typeof AppPackagesIndexRoute
  AppTeamIndexRoute: typeof AppTeamIndexRoute
  AppAdminPluginsDocsRoute: typeof AppAdminPluginsDocsRoute
  AppAdminPluginsSigningKeysRoute: typeof AppAdminPluginsSigningKeysRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessManagementRoute: AppAccessManagementRoute,
  AppAffiliateRoute: AppAffiliateRoute,
  AppAgencyRoute: AppAgencyRoute,
  AppAiTokensMasterRoute: AppAiTokensMasterRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApiDocsRoute: AppApiDocsRoute,
  AppBillingsRoute: AppBillingsRoute,
  AppBioLinkRoute: AppBioLinkRoute,
  AppCreatorsProgramRoute: AppCreatorsProgramRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeadsCapturedRoute: AppLeadsCapturedRoute,
  AppPlatformAdminsRoute: AppPlatformAdminsRoute,
  AppRbacMasterRoute: AppRbacMasterRoute,
  AppSchedulerRoute: AppSchedulerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShortLinksRoute: AppShortLinksRoute,
  AppAdminAffiliatesRoute: AppAdminAffiliatesRoute,
  AppAdminCapabilitiesRoute: AppAdminCapabilitiesRoute,
  AppAdminCreatorManagementRoute: AppAdminCreatorManagementRouteWithChildren,
  AppAdminCreatorsRoute: AppAdminCreatorsRouteWithChildren,
  AppAdminEmailTemplatesRoute: AppAdminEmailTemplatesRoute,
  AppAdminImpersonationRoute: AppAdminImpersonationRoute,
  AppAdminPluginsRoute: AppAdminPluginsRoute,
  AppAdminUsersRoute: AppAdminUsersRouteWithChildren,
  AppAutomationsNewRoute: AppAutomationsNewRoute,
  AppModuleRegistryParentIdRoute: AppModuleRegistryParentIdRoute,
  AppModuleRegistryDocsRoute: AppModuleRegistryDocsRoute,
  AppModuleRegistryNewRoute: AppModuleRegistryNewRoute,
  AppPackagesPackageIdRoute: AppPackagesPackageIdRoute,
  AppPackagesAssignRoute: AppPackagesAssignRoute,
  AppPackagesNewRoute: AppPackagesNewRoute,
  AppPluginsKeyRoute: AppPluginsKeyRoute,
  AppTeamInviteRoute: AppTeamInviteRoute,
  AppAutomationsIndexRoute: AppAutomationsIndexRoute,
  AppModuleRegistryIndexRoute: AppModuleRegistryIndexRoute,
  AppPackagesIndexRoute: AppPackagesIndexRoute,
  AppTeamIndexRoute: AppTeamIndexRoute,
  AppAdminPluginsDocsRoute: AppAdminPluginsDocsRoute,
  AppAdminPluginsSigningKeysRoute: AppAdminPluginsSigningKeysRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  CheckoutRoute: CheckoutRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  AuthHandoffRoute: AuthHandoffRoute,
  LeadsCapturedSlugRoute: LeadsCapturedSlugRoute,
  AuthGoogleCompleteRoute: AuthGoogleCompleteRoute,
  OauthMetaCompleteRoute: OauthMetaCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
