/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsCapturedSlugRouteImport } from './routes/leads-captured.$slug'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppShortLinksRouteImport } from './routes/_app/short-links'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSchedulerRouteImport } from './routes/_app/scheduler'
import { Route as AppRbacMasterRouteImport } from './routes/_app/rbac-master'
import { Route as AppLeadsCapturedRouteImport } from './routes/_app/leads-captured'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBioLinkRouteImport } from './routes/_app/bio-link'
import { Route as AppBillingsRouteImport } from './routes/_app/billings'
import { Route as AppApiDocsRouteImport } from './routes/_app/api-docs'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAgencyRouteImport } from './routes/_app/agency'
import { Route as AppAffiliateRouteImport } from './routes/_app/affiliate'
import { Route as AppAutomationsIndexRouteImport } from './routes/_app/automations.index'
import { Route as OauthMetaCompleteRouteImport } from './routes/oauth.meta.complete'
import { Route as AuthGoogleCompleteRouteImport } from './routes/auth.google.complete'
import { Route as AppAutomationsNewRouteImport } from './routes/_app/automations.new'
import { Route as AppAdminEmailTemplatesRouteImport } from './routes/_app/admin.email-templates'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsCapturedSlugRoute = LeadsCapturedSlugRouteImport.update({
  id: '/leads-captured/$slug',
  path: '/leads-captured/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppShortLinksRoute = AppShortLinksRouteImport.update({
  id: '/short-links',
  path: '/short-links',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSchedulerRoute = AppSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AppRoute,
} as any)
const AppRbacMasterRoute = AppRbacMasterRouteImport.update({
  id: '/rbac-master',
  path: '/rbac-master',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsCapturedRoute = AppLeadsCapturedRouteImport.update({
  id: '/leads-captured',
  path: '/leads-captured',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBioLinkRoute = AppBioLinkRouteImport.update({
  id: '/bio-link',
  path: '/bio-link',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingsRoute = AppBillingsRouteImport.update({
  id: '/billings',
  path: '/billings',
  getParentRoute: () => AppRoute,
} as any)
const AppApiDocsRoute = AppApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAgencyRoute = AppAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateRoute = AppAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsIndexRoute = AppAutomationsIndexRouteImport.update({
  id: '/automations/',
  path: '/automations/',
  getParentRoute: () => AppRoute,
} as any)
const OauthMetaCompleteRoute = OauthMetaCompleteRouteImport.update({
  id: '/oauth/meta/complete',
  path: '/oauth/meta/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCompleteRoute = AuthGoogleCompleteRouteImport.update({
  id: '/auth/google/complete',
  path: '/auth/google/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAutomationsNewRoute = AppAutomationsNewRouteImport.update({
  id: '/automations/new',
  path: '/automations/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmailTemplatesRoute = AppAdminEmailTemplatesRouteImport.update({
  id: '/admin/email-templates',
  path: '/admin/email-templates',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/checkout': typeof CheckoutRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/affiliate': typeof AppAffiliateRoute
  '/agency': typeof AppAgencyRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api-docs': typeof AppApiDocsRoute
  '/billings': typeof AppBillingsRoute
  '/bio-link': typeof AppBioLinkRoute
  '/dashboard': typeof AppDashboardRoute
  '/leads-captured': typeof AppLeadsCapturedRoute
  '/rbac-master': typeof AppRbacMasterRoute
  '/scheduler': typeof AppSchedulerRoute
  '/settings': typeof AppSettingsRoute
  '/short-links': typeof AppShortLinksRoute
  '/team': typeof AppTeamRoute
  '/leads-captured/$slug': typeof LeadsCapturedSlugRoute
  '/admin/email-templates': typeof AppAdminEmailTemplatesRoute
  '/automations/new': typeof AppAutomationsNewRoute
  '/auth/google/complete': typeof AuthGoogleCompleteRoute
  '/oauth/meta/complete': typeof OauthMetaCompleteRoute
  '/automations/': typeof AppAutomationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/checkout': typeof CheckoutRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/affiliate': typeof AppAffiliateRoute
  '/agency': typeof AppAgencyRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api-docs': typeof AppApiDocsRoute
  '/billings': typeof AppBillingsRoute
  '/bio-link': typeof AppBioLinkRoute
  '/dashboard': typeof AppDashboardRoute
  '/leads-captured': typeof AppLeadsCapturedRoute
  '/rbac-master': typeof AppRbacMasterRoute
  '/scheduler': typeof AppSchedulerRoute
  '/settings': typeof AppSettingsRoute
  '/short-links': typeof AppShortLinksRoute
  '/team': typeof AppTeamRoute
  '/leads-captured/$slug': typeof LeadsCapturedSlugRoute
  '/admin/email-templates': typeof AppAdminEmailTemplatesRoute
  '/automations/new': typeof AppAutomationsNewRoute
  '/auth/google/complete': typeof AuthGoogleCompleteRoute
  '/oauth/meta/complete': typeof OauthMetaCompleteRoute
  '/automations': typeof AppAutomationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/checkout': typeof CheckoutRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/_app/affiliate': typeof AppAffiliateRoute
  '/_app/agency': typeof AppAgencyRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/api-docs': typeof AppApiDocsRoute
  '/_app/billings': typeof AppBillingsRoute
  '/_app/bio-link': typeof AppBioLinkRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leads-captured': typeof AppLeadsCapturedRoute
  '/_app/rbac-master': typeof AppRbacMasterRoute
  '/_app/scheduler': typeof AppSchedulerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/short-links': typeof AppShortLinksRoute
  '/_app/team': typeof AppTeamRoute
  '/leads-captured/$slug': typeof LeadsCapturedSlugRoute
  '/_app/admin/email-templates': typeof AppAdminEmailTemplatesRoute
  '/_app/automations/new': typeof AppAutomationsNewRoute
  '/auth/google/complete': typeof AuthGoogleCompleteRoute
  '/oauth/meta/complete': typeof OauthMetaCompleteRoute
  '/_app/automations/': typeof AppAutomationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/checkout'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/affiliate'
    | '/agency'
    | '/analytics'
    | '/api-docs'
    | '/billings'
    | '/bio-link'
    | '/dashboard'
    | '/leads-captured'
    | '/rbac-master'
    | '/scheduler'
    | '/settings'
    | '/short-links'
    | '/team'
    | '/leads-captured/$slug'
    | '/admin/email-templates'
    | '/automations/new'
    | '/auth/google/complete'
    | '/oauth/meta/complete'
    | '/automations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/checkout'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/affiliate'
    | '/agency'
    | '/analytics'
    | '/api-docs'
    | '/billings'
    | '/bio-link'
    | '/dashboard'
    | '/leads-captured'
    | '/rbac-master'
    | '/scheduler'
    | '/settings'
    | '/short-links'
    | '/team'
    | '/leads-captured/$slug'
    | '/admin/email-templates'
    | '/automations/new'
    | '/auth/google/complete'
    | '/oauth/meta/complete'
    | '/automations'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/accept-invite'
    | '/checkout'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/_app/affiliate'
    | '/_app/agency'
    | '/_app/analytics'
    | '/_app/api-docs'
    | '/_app/billings'
    | '/_app/bio-link'
    | '/_app/dashboard'
    | '/_app/leads-captured'
    | '/_app/rbac-master'
    | '/_app/scheduler'
    | '/_app/settings'
    | '/_app/short-links'
    | '/_app/team'
    | '/leads-captured/$slug'
    | '/_app/admin/email-templates'
    | '/_app/automations/new'
    | '/auth/google/complete'
    | '/oauth/meta/complete'
    | '/_app/automations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  LeadsCapturedSlugRoute: typeof LeadsCapturedSlugRoute
  AuthGoogleCompleteRoute: typeof AuthGoogleCompleteRoute
  OauthMetaCompleteRoute: typeof OauthMetaCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads-captured/$slug': {
      id: '/leads-captured/$slug'
      path: '/leads-captured/$slug'
      fullPath: '/leads-captured/$slug'
      preLoaderRoute: typeof LeadsCapturedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/short-links': {
      id: '/_app/short-links'
      path: '/short-links'
      fullPath: '/short-links'
      preLoaderRoute: typeof AppShortLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scheduler': {
      id: '/_app/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof AppSchedulerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rbac-master': {
      id: '/_app/rbac-master'
      path: '/rbac-master'
      fullPath: '/rbac-master'
      preLoaderRoute: typeof AppRbacMasterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads-captured': {
      id: '/_app/leads-captured'
      path: '/leads-captured'
      fullPath: '/leads-captured'
      preLoaderRoute: typeof AppLeadsCapturedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bio-link': {
      id: '/_app/bio-link'
      path: '/bio-link'
      fullPath: '/bio-link'
      preLoaderRoute: typeof AppBioLinkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billings': {
      id: '/_app/billings'
      path: '/billings'
      fullPath: '/billings'
      preLoaderRoute: typeof AppBillingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-docs': {
      id: '/_app/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof AppApiDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agency': {
      id: '/_app/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AppAgencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate': {
      id: '/_app/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AppAffiliateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations/': {
      id: '/_app/automations/'
      path: '/automations'
      fullPath: '/automations/'
      preLoaderRoute: typeof AppAutomationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/meta/complete': {
      id: '/oauth/meta/complete'
      path: '/oauth/meta/complete'
      fullPath: '/oauth/meta/complete'
      preLoaderRoute: typeof OauthMetaCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/complete': {
      id: '/auth/google/complete'
      path: '/auth/google/complete'
      fullPath: '/auth/google/complete'
      preLoaderRoute: typeof AuthGoogleCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/automations/new': {
      id: '/_app/automations/new'
      path: '/automations/new'
      fullPath: '/automations/new'
      preLoaderRoute: typeof AppAutomationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/email-templates': {
      id: '/_app/admin/email-templates'
      path: '/admin/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AppAdminEmailTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAffiliateRoute: typeof AppAffiliateRoute
  AppAgencyRoute: typeof AppAgencyRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApiDocsRoute: typeof AppApiDocsRoute
  AppBillingsRoute: typeof AppBillingsRoute
  AppBioLinkRoute: typeof AppBioLinkRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeadsCapturedRoute: typeof AppLeadsCapturedRoute
  AppRbacMasterRoute: typeof AppRbacMasterRoute
  AppSchedulerRoute: typeof AppSchedulerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShortLinksRoute: typeof AppShortLinksRoute
  AppTeamRoute: typeof AppTeamRoute
  AppAdminEmailTemplatesRoute: typeof AppAdminEmailTemplatesRoute
  AppAutomationsNewRoute: typeof AppAutomationsNewRoute
  AppAutomationsIndexRoute: typeof AppAutomationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAffiliateRoute: AppAffiliateRoute,
  AppAgencyRoute: AppAgencyRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApiDocsRoute: AppApiDocsRoute,
  AppBillingsRoute: AppBillingsRoute,
  AppBioLinkRoute: AppBioLinkRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeadsCapturedRoute: AppLeadsCapturedRoute,
  AppRbacMasterRoute: AppRbacMasterRoute,
  AppSchedulerRoute: AppSchedulerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShortLinksRoute: AppShortLinksRoute,
  AppTeamRoute: AppTeamRoute,
  AppAdminEmailTemplatesRoute: AppAdminEmailTemplatesRoute,
  AppAutomationsNewRoute: AppAutomationsNewRoute,
  AppAutomationsIndexRoute: AppAutomationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  CheckoutRoute: CheckoutRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  LeadsCapturedSlugRoute: LeadsCapturedSlugRoute,
  AuthGoogleCompleteRoute: AuthGoogleCompleteRoute,
  OauthMetaCompleteRoute: OauthMetaCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
